// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
try {
  // Only present in local dev; in Docker, env vars come from docker-compose.
  require("dotenv/config");
} catch {
  // dotenv not installed in production image — env vars are injected by the container runtime.
}
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
